### ISSUE TITLE
Add renderer or pretty-printer

### ISSUE THREAD

**Issue by chshersh** [glguy/toml-parser#1]
It's easy to parse `.toml` files with this package! But there's no function to render `Value` data type into `Text` which might be useful.

**Comment by tom-audm** [comment]
Is this a planned enhancement? Love the parsing library but our use-case requires rendering as well.

**Comment by chshersh** [comment]
@tom-audm I've been working on the `tomland` library in @kowainik for bidirectional TOML serialisation during the last couple of years. The library provides both parsing and rendering, and supports the latest released TOML specification. And it is the official Haskell library for TOML at the moment.

* https://github.com/kowainik/tomland

You can give it a try and provide your feedback 🙂 We're planning to release `tomland-1.3.0.0` very soon, and we've been very busy with preparing new features and major documentation improvements for the release during the last week.

**Comment by tom-audm** [comment]
@chshersh what do you mean by "it is the official Haskell library for TOML at the moment"?

A benefit of toml-parser is the minimal dependencies; it would be nice to have a simple renderer/pretty printer for it.

**Comment by chshersh** [comment]
@tom-audm I mean that it's the only Haskell library that supports the latest released TOML spec 0.5.0 and it's mentioned in the TOML wiki as an implementation:

* https://github.com/toml-lang/toml/wiki#v050-compliant

`tomland` is rather minimal in dependencies too. It depends only on boot libraries (except `megaparsec`), which doesn't contribute much to build dependencies.
