### ISSUE TITLE
Can base lower bound be relaxed?

### ISSUE THREAD

**Issue by jgm** [glguy/toml-parser#12]
I'd like to use this, but I need to support at least ghc 9.0.
Is there a specific reason for the current base lower bound, or could that be relaxed?  (This might also mean relaxing template-haskell bounds and perhaps other things.)

**Comment by glguy** [comment]
The only reason was me defaulting to the common policy of supporting the last 3 GHC releases and it being hard to test older versions on my M1 mac. I'll see if things work on older GHCs and update if it works out.

**Comment by glguy** [comment]
Released to hackage as 1.1.1.0

**Comment by jgm** [comment]
Excellent, thanks very much!
