### ISSUE TITLE
no instance for `ToValue UTCTime` 

### ISSUE THREAD

**Issue by MangoIV** [glguy/toml-parser#19]
toml allows for ISO8601 formatted timestamps, this includes times without offset. Hence there should be the possibility to format a `UTCTime`. see https://toml.io/en/v1.0.0#local-date-time

**Comment by glguy** [comment]
@MangoIV how's that look?

**Comment by MangoIV** [comment]
Looks good! I would have expected that there would have be a new token but this solution is even better!
