### ISSUE TITLE
Specify which version of Toml the parser conforms to

### ISSUE THREAD

**Issue by szabi** [glguy/toml-parser#5]
And ideally make an entry at the toml github wiki.

Given how much toml has evolved between 0.1 and 0.5 (most recent as of today), I think it would be valuable information for the user which version files `toml-parser` will consume.

**Comment by MyriaCore** [comment]
bump?

**Comment by brandonchinn178** [comment]
Working on upgrading this library to be v1.0.0 compatible (see #10). To update this thread, it seems like, through my testing, this library is currently on v0.4.0. But hopefully I can finish #10 soon, and get this library on v1.0.0 (and mention it in the README)

**Comment by glguy** [comment]
Resolved in toml-parser-1.0.0.0 - now supports TOML 1.0.0
